### ISSUE TITLE
現行のプログラムだとうまくいきそうにないです。

### ISSUE THREAD

**Issue by solt-n4muru** [solt-n4muru/life_game#2]
今困っていること。
・ファイル分けのclassと継承がうまく行ってるかわからない。
・pygameのscreenの仕様がよくわかってない。
・クラスを継承したはずなんだけど、データが共有されてなさそう。
・画面の更新がクソ重い可能性がある。

詳しくは、作ったプログラム動かしてみてほしい。

**Comment by moqumo** [comment]
表示に関してはできました．（feature_cellsの中にある）
![image](https://github.com/user-attachments/assets/ae1cc478-ba6e-4319-887e-08202b35d9b7)

**Comment by moqumo** [comment]
動きました．tests/test_cells.pyを実行してみて

**Comment by iyusei-76** [comment]
ファイルの階層的に実行がうまくいかなかったですが、動きは確認できました。

**Comment by iyusei-76** [comment]
残りフィールドの下線とファイルの問題が解消したらissueを閉じたいと思います。
